---
- name: Converge
  hosts: all
  pre_tasks:
  - name: add user group
    user:
      name: '{{ installation_os_group }}'
      state: present
  - name: add user
    user:
      name: '{{ installation_os_user }}'
      group: '{{ installation_os_group }}'

  - include_tasks: redhat.yml
    when: ansible_os_family == "RedHat"

  - include_tasks: debian.yml
    when: ansible_os_family == "Debian"

  roles:
    - { role: bassinator.usbbackup, usbdrive_unit: 'mnt-usbbackup', mount_point: '/mnt/usbbackup'}

  post_tasks:
    - name: create testfiles to be backuped
      file:
        path: '/home/{{ installation_os_user }}/testfile'
        state: touch
        modification_time: "preserve"
        access_time: "preserve"
    - name: test usbbackup
      script: test.sh
      args:
        creates: '/mnt/usbbackup/ttt'
